//
// This is a file generated by Phase-Locked Loop wizard.
// Please do not edit this file!
// Generated time: 08/13/2025 12:19:28
// Version: Fuxi fuxi win64
// Wizard name: Phase-Locked Loop 1.0b
//
// ============================================================
// File Name: pll_v1.v
// IP core : pll
// Device name: H7P20N0L128-M3H1C7
// ============================================================

module pll_v1(
    clkin0,
    locked,
    clkout0
);

input clkin0;
output locked;
output clkout0;

wire gen_pdb;
pll_detector u_det (
        .refclk (clkin0),
        .pdb (1'b1),
        .pll_clk (clkout0),
        .pll_pd (gen_pdb)
);

PLL_TOP #(
        .SEL_FBPATH (1'b0),
        .pll_sel ("auto"),
        .input_freq ("48"),
        .CPSEL_FN (6'b101000),
        .CP_AUTO_ENB (1'b0),
        .BK (4'b1010),
        .CALIB_VREF (2'b01),
        .CKSEL (1'b0),
        .CPSEL_CR (4'b1000),
        .LPF (3'b111),
        .FBDLY (7'b0000000),
        .PFBSEL (3'b000),
        .VCO_INI_SEL (1'b0),
        .RST_REG_ENB (1'b0),
        .TRIM_CAP (3'b100),
        .EN_LOWSPD (1'b1),
        .VRSEL (2'b10),
        .CASCADE_EN (1'b0),
        .FRAC_C0 (3'b000),
        .FRAC_FB (3'b000),
        .MKEN0 (1'b1),
        .BPS0 (1'b0),
        .DIVC0 (7'b0001011),
        .GATE_BPS0 (1'b0),
        .P0SEL (3'b000),
        .CO0DLY (7'b0000000),
        .ADD_HALF0 (1'b0),
        .CO0DUTY (7'b0000110),
        .MKEN1 (1'b0),
        .BPS1 (1'b0),
        .DIVC1 (7'b0001000),
        .GATE_BPS1 (1'b0),
        .P1SEL (3'b000),
        .CO1DLY (7'b0000000),
        .ADD_HALF1 (1'b1),
        .CO1DUTY (7'b0000100),
        .MKEN2 (1'b0),
        .BPS2 (1'b0),
        .DIVC2 (7'b0001000),
        .GATE_BPS2 (1'b0),
        .P2SEL (3'b000),
        .CO2DLY (7'b0000000),
        .ADD_HALF2 (1'b1),
        .CO2DUTY (7'b0000100),
        .MKEN3 (1'b0),
        .BPS3 (1'b0),
        .DIVC3 (7'b0001000),
        .GATE_BPS3 (1'b0),
        .P3SEL (3'b000),
        .CO3DLY (7'b0000000),
        .ADD_HALF3 (1'b1),
        .CO3DUTY (7'b0000100),
        .MKEN4 (1'b0),
        .BPS4 (1'b0),
        .DIVC4 (7'b0001000),
        .GATE_BPS4 (1'b0),
        .P4SEL (3'b000),
        .CO4DLY (7'b0000000),
        .ADD_HALF4 (1'b1),
        .CO4DUTY (7'b0000100),
        .MKEN5 (1'b0),
        .BPS5 (1'b0),
        .DIVC5 (7'b0001000),
        .GATE_BPS5 (1'b0),
        .P5SEL (3'b000),
        .CO5DLY (7'b0000000),
        .ADD_HALF5 (1'b1),
        .CO5DUTY (7'b0000100),
        .MKEN6 (1'b0),
        .BPS6 (1'b0),
        .DIVC6 (7'b0001000),
        .GATE_BPS6 (1'b0),
        .P6SEL (3'b000),
        .CO6DLY (7'b0000000),
        .ADD_HALF6 (1'b1),
        .CO6DUTY (7'b0000100),
        .DIVN (7'b0000000),
        .DIVM (7'b0001110),
        .EN_HOLD (1'b1),
        .LD_HOLD (1'b0),
        .LD_CLKDIV (1'b0),
        .LD_EN_ACC (1'b0),
        .LD_RT_INRNG (1'b1),
        .LD_RT_OUTRNG (1'b1),
        .LD_MUX (1'b0),
        .CNT_SEL (2'b01),
        .FORCE_LOCK (1'b0),
        .INRNG_SEL (3'b010),
        .OUTRNG_SEL (3'b010),
        .LD_EN (1'b1),
        .GATE_ENB (1'b1),
        .CALIB_DIR (1'b0),
        .CALIB_EN (1'b1),
        .CALIB_MANUAL (4'b1000),
        .CALIB_CYCLE (3'b011),
        .CALIB_EN_DYN (1'b0),
        .CALIB_CLKDIV (1'b0),
        .CALIB_STB_TIME (3'b011),
        .CALIB_THRESHOLD (3'b011),
        .RST_SEL (2'b01),
        .PDB_SEL (2'b11),
        .FP_CFG_EN (1'b0),
        .SSC_ACCSEL (2'b00),
        .SSC_EN (1'b0),
        .SSC_MODE (1'b0),
        .SSC_TRI_PEAK (2'b00),
        .DIVACC (2'b00),
        .DIVSSC (7'b0000000)
)
pll_u0 (
        .PLLCK0 (clkin0),
        .PLLCK1 (),
        .PSCK (),
        .PSDIR (),
        .PSEN (1'b1),
        .PSDONE (),
        .PSSEL (3'b000),
        .FP_DUTY_FORCE (),
        .FP_ADD_HALF (),
        .FP_DIV (),
        .FP_DUTY (),
        .FP_SEL (3'b000),
        .FP_SW (1'b1),
        .FP_CF_CLK (),
        .FP_CF_EN (),
        .FP_CF_IN (),
        .FP_CF_UP (),
        .FP_CF_SEL (),
        .FBIN (),
        .PDB (gen_pdb),
        .RSTPLL (),
        .CO0 (clkout0),
        .CO1 (),
        .CO2 (),
        .CO3 (),
        .CO4 (),
        .CO5 (),
        .CO6 (),
        .PLOCK (locked)
);

endmodule

module pll_detector( 
    refclk,
    pdb,
    pll_clk,
    pll_pd
);

input refclk, pdb;
input pll_clk;
output pll_pd;

reg [3:0] genrst = 0;
wire genrsten = genrst != 4'b1010;

wire rsts;
assign rsts = pdb & (!genrsten);

always @ (posedge refclk) begin
    if(genrsten)
        genrst <= genrst + 1;
end

reg [5:0] pll_state = 0;
reg [21:0] state = 0;

wire pllwork = (pll_state == 6'b100110);
always @ (posedge refclk or negedge rsts) begin
    if(!rsts)
        state <= 'h0;
    else if(~pllwork)
        state <= state + 1;
    else
        state <= state;
end

always @ (posedge pll_clk or negedge rsts) begin
    if(!rsts)
        pll_state <= 0;
    else if(~pllwork)
        pll_state <= pll_state + 1;
    else
        pll_state <= pll_state;
end

wire pdb_gen = state[21:16] != 6'b100110;
assign pll_pd = pdb_gen & pdb;

endmodule


// ============================================================
//                  pll Setting
//
// Warning: This part is read by Fuxi, please don't modify it.
// ============================================================
// Device          : H7P20N0L128-M3H1C7
// Module          : pll_v1
// IP core         : pll
// IP Version      : 1

// BandWidth       : Medium
// Bypass0         : false
// Bypass1         : false
// Bypass2         : false
// Bypass3         : false
// Bypass4         : false
// Bypass5         : false
// Bypass6         : false
// C0              : 11
// C1              : 8
// C2              : 8
// C3              : 8
// C4              : 8
// C5              : 8
// C6              : 8
// CascadeOutputClock: false
// Clkin0Enable    : true
// Clkin1Enable    : false
// Clkout0UseFrac  : false
// ClkoutNum       : 1
// Delay0          : 0
// Delay1          : 0
// Delay2          : 0
// Delay3          : 0
// Delay4          : 0
// Delay5          : 0
// Delay6          : 0
// DelayUnit       : degree
// DeskewMode      : None
// DutyCycle0      : 0.5
// DutyCycle1      : 0.5
// DutyCycle2      : 0.5
// DutyCycle3      : 0.5
// DutyCycle4      : 0.5
// DutyCycle5      : 0.5
// DutyCycle6      : 0.5
// DynOutputClockSwitch: false
// DynPhaseShiftEn : false
// Enable0         : true
// Enable1         : false
// Enable2         : false
// Enable3         : false
// Enable4         : false
// Enable5         : false
// Enable6         : false
// ExpectFreq0     : 60
// ExpectFreq1     : -100
// ExpectFreq2     : -100
// ExpectFreq3     : -100
// ExpectFreq4     : -100
// ExpectFreq5     : -100
// ExpectFreq6     : -100
// ForceLocked     : false
// FracDivCO0En    : false
// FracDivForFeadBackEn: false
// Gate0           : false
// Gate1           : false
// Gate2           : false
// Gate3           : false
// Gate4           : false
// Gate5           : false
// Gate6           : false
// GclkCcbEnable   : false
// InputFreq       : 48
// Location        : auto
// M               : 14
// N               : 0
// Phase0          : 0
// Phase1          : 0
// Phase2          : 0
// Phase3          : 0
// Phase4          : 0
// Phase5          : 0
// Phase6          : 0
// PortLocked      : true
// PowerMode       : always_on
// PowerSave       : true
// ResetMode       : ccb
// Sdc Files       : 
// Simulation Files: 
// SpreadEnable    : false
// SpreadFreq      : 30
// SpreadMode      : Down
// SpreadRange     : 0
// SpreadTriPeak   : 32
// Synthesis Files : 
// UseLockGate     : false
// VcoCalibration  : false
// VcoDivide       : 0
