//
// This is a file generated by EMB wizard.
// Please do not edit this file!
// Generated time: 08/01/2024 18:15:02
// Version: Fuxi fx2023.1 win64
// Wizard name: EMB 1.0b
//
// ============================================================
// File Name: hme_ip_emb_eth.v
// IP core : emb
// Device name: P2P50N0V324-M4H1C7
// ============================================================

module hme_ip_emb_eth (clkr, clkw, cer, cew, rstnr, ar, aw, dw, qr);
input clkr;
input clkw;
input cer;
input cew;
input rstnr;
input [7:0] ar;
input [7:0] aw;
input [15:0] dw;
output [15:0] qr;

wire vcc_net;
wire gnd_net;

assign vcc_net = 1;
assign gnd_net = 0;
P0_EMB9K #(
		.init_file (""),
		.is_initialized (0),
		.byte_write_enable (0),
		.cea_inv (1'b0),
		.ceb_inv (1'b0),
		.clka_inv (1'b0),
		.clkb_inv (1'b0),
		.extension_mode ("power"),
		.outreg_a (1'b0),
		.outreg_b (1'b0),
		.rammode ("sdp"),
		.regcea_inv (1'b0),
		.regceb_inv (1'b0),
		.regsra_inv (1'b0),
		.regsrb_inv (1'b0),
		.reset_value (18'h0000),
		.use_parity (1'b0),
		.wea_inv (1'b0),
		.web_inv (1'b0),
		.width_a (18),
		.width_b (18),
		.writemode_a ("write_first"),
		.writemode_b ("write_first")
	)
	emb_0 (
		.doa ({qr[15], qr[14], qr[13], qr[12], qr[11], qr[10], qr[9], qr[8], qr[7], qr[6], qr[5], qr[4], qr[3], qr[2], qr[1], qr[0]}),
		.dob (),
		.dopa (),
		.dopb (),
		.addra ({gnd_net, gnd_net, gnd_net, gnd_net, gnd_net, ar[7], ar[6], ar[5], ar[4], ar[3], ar[2], ar[1], ar[0]}),
		.addrb ({gnd_net, gnd_net, gnd_net, gnd_net, gnd_net, aw[7], aw[6], aw[5], aw[4], aw[3], aw[2], aw[1], aw[0]}),
		.clka (clkr),
		.clkb (clkw),
		.dia (),
		.dib ({dw[15], dw[14], dw[13], dw[12], dw[11], dw[10], dw[9], dw[8], dw[7], dw[6], dw[5], dw[4], dw[3], dw[2], dw[1], dw[0]}),
		.dipa (),
		.dipb (),
		.cea (cer),
		.ceb (cew),
		.regcea (vcc_net),
		.regceb (),
		.regsra (rstnr),
		.regsrb (vcc_net),
		.wea ({gnd_net, gnd_net}),
		.web ({vcc_net, vcc_net})
	);

endmodule

// ============================================================
//                  emb Setting
//
// Warning: This part is read by Fuxi, please don't modify it.
// ============================================================
// Device          : P2P50N0V324-M4H1C7
// Module          : hme_ip_emb_eth
// IP core         : emb
// IP Version      : 1

// AddrUsedA       : 8
// ByteWriteEn     : false
// DataUsedA       : 16
// DataUsedB       : 16
// DepthUsedA      : 256
// EmbResource     : EMB9K
// EmbType         : sdp
// ErrorInjectMode : None
// InitFile        : 
// RegoutA         : false
// RegoutB         : false
// RegoutEnA       : false
// RegoutEnB       : false
// ResetValue      : 
// Simulation Files: 
// SplitEmb        : false
// SplitInfo       : 16,256;block_0:16,512,0,0,0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15
// Synthesis Files : 
// UseEccEn        : false
// WriteModeA      : Write First
// WriteModeB      : Write First

