//
// This is a file generated by Ethernet MAC wizard.
// Please do not edit this file!
// Generated time: 07/13/2025 08:45:10
// Version: Fuxi fx2023.1 win64
// Wizard name: Ethernet MAC 3.0a
//
// ============================================================
// File Name: EthernetMAC_v3.v
// IP core : EthernetMAC
// Device name: H7P20N0L128-M3H1C7
// ============================================================

module EthernetMAC_v3(
    clk_tx_i,
    clk_rx_i,
    clk_app_i,
    rst_clk_rx_n,
    rst_clk_tx_n,
    rst_clk_app_n,
    s_ahb_addr,
    s_ahb_sel,
    s_ahb_write,
    s_ahb_trans,
    s_ahb_wdata,
    s_ahb_readyout,
    s_ahb_rdata,
    phy_txen_o,
    phy_txer_o,
    phy_txd_o,
    phy_rxd_i,
    phy_crs_i,
    phy_col_i,
    phy_rxdv_i,
    phy_rxer_i,
    gmii_mdc_o,
    gmii_mdi_i,
    gmii_mdo_o,
    gmii_mdo_o_e,
    irq
);

localparam DATA_ACCESS_USE_MCU = 1'b1;
localparam BASE_ADDR = 32'ha0000000;

input clk_tx_i;
input clk_rx_i;
input clk_app_i;
input rst_clk_rx_n;
input rst_clk_tx_n;
input rst_clk_app_n;
input [31:0] s_ahb_addr;
input s_ahb_sel;
input s_ahb_write;
input [1:0] s_ahb_trans;
input [31:0] s_ahb_wdata;
output s_ahb_readyout;
output [31:0] s_ahb_rdata;
output phy_txen_o;
output phy_txer_o;
output [7:0] phy_txd_o;
input [7:0] phy_rxd_i;
input phy_crs_i;
input phy_col_i;
input phy_rxdv_i;
input phy_rxer_i;
output gmii_mdc_o;
input gmii_mdi_i;
output gmii_mdo_o;
output gmii_mdo_o_e;
output irq;

hme_ip_eth_mac_top_ahb_f_1k_v3 #(
        .DATA_ACCESS_USE_MCU (DATA_ACCESS_USE_MCU),
        .BASE_ADDR (BASE_ADDR)
)
u_ethernet_inst (
        .clk_tx_i (clk_tx_i),
        .clk_rx_i (clk_rx_i),
        .clk_app_i (clk_app_i),
        .rst_clk_rx_n (rst_clk_rx_n),
        .rst_clk_tx_n (rst_clk_tx_n),
        .rst_clk_app_n (rst_clk_app_n),
        .s_ahb_addr (s_ahb_addr),
        .s_ahb_sel (s_ahb_sel),
        .s_ahb_write (s_ahb_write),
        .s_ahb_trans (s_ahb_trans),
        .s_ahb_wdata (s_ahb_wdata),
        .s_ahb_readyout (s_ahb_readyout),
        .s_ahb_rdata (s_ahb_rdata),
        .phy_txen_o (phy_txen_o),
        .phy_txer_o (phy_txer_o),
        .phy_crs_i (phy_crs_i),
        .phy_col_i (phy_col_i),
        .phy_rxdv_i (phy_rxdv_i),
        .phy_rxer_i (phy_rxer_i),
        .gmii_mdc_o (gmii_mdc_o),
        .gmii_mdi_i (gmii_mdi_i),
        .gmii_mdo_o (gmii_mdo_o),
        .gmii_mdo_o_e (gmii_mdo_o_e),
        .irq (irq),
        .phy_txd_o (phy_txd_o),
        .phy_rxd_i (phy_rxd_i)
);

endmodule

// ============================================================
//                  EthernetMAC Setting
//
// Warning: This part is read by Fuxi, please don't modify it.
// ============================================================
// Device          : H7P20N0L128-M3H1C7
// Module          : EthernetMAC_v3
// IP core         : EthernetMAC
// IP Version      : 3

// Simulation Files: ../ip_core/ethernet_mac_v3/sim/P0_P2/hme_ip_ahb2mci_ahb_v3.vp ../ip_core/ethernet_mac_v3/sim/P0_P2/hme_ip_emb_eth.v ../ip_core/ethernet_mac_v3/sim/P0_P2/hme_ip_eth_mac_core_f_1k_v3.vp ../ip_core/ethernet_mac_v3/sim/P0_P2/hme_ip_eth_mac_top_ahb_f_1k_v3.vp ../ip_core/ethernet_mac_v3/sim/P0_P2/hme_ip_rx_dpram_768x32_ahb_v3.vp ../ip_core/ethernet_mac_v3/sim/P0_P2/hme_ip_tx_dpram_768x32_ahb_v3.vp ../ip_core/ethernet_mac_v3/sim/P0_P2/hme_ip_tr_mem_ctrl_ahb_v3.vp
// Synthesis Files : src/P0_P2/hme_ip_ahb2mci_ahb_v3.v src/P0_P2/hme_ip_emb_eth.v src/P0_P2/hme_ip_eth_mac_core_f_1k_v3.v src/P0_P2/hme_ip_eth_mac_top_ahb_f_1k_v3.v src/P0_P2/hme_ip_rx_dpram_768x32_ahb_v3.v src/P0_P2/hme_ip_tx_dpram_768x32_ahb_v3.v src/P0_P2/hme_ip_tr_mem_ctrl_ahb_v3.v
// baseaddress     : a0000000
// data access by FPGA: false
// speedmode       : 1000M
// workmode        : Full Duplex
