//
// This is a file generated by Rgmii wizard.
// Please do not edit this file!
// Generated time: 03/21/2025 14:11:24
// Version: Fuxi fuxi win64
// Wizard name: Rgmii 1.0a
//
// ============================================================
// File Name: rgmii_v1.v
// IP core : rgmii
// Device name: H7P20N0V213-S1H1C7
// ============================================================

module rgmii_v1(
    clk_eth,
    clk_eth_90d,
    i_tx_clk_d0,
    i_tx_clk_d1,
    gmii_tx_en,
    gmii_txd,
    gmii_tx_er,
    rgmii_txc,
    rgmii_tx_ctl,
    rgmii_txd,
    rgmii_rxc,
    rgmii_rx_ctl,
    rgmii_rxd,
    gmii_rx_clk,
    gmii_rx_dv,
    gmii_rx_er,
    gmii_rxd
);

input clk_eth;
input clk_eth_90d;
input i_tx_clk_d0;
input i_tx_clk_d1;
input gmii_tx_en;
input [7:0] gmii_txd;
input gmii_tx_er;
output rgmii_txc;
output rgmii_tx_ctl;
output [3:0] rgmii_txd;
input rgmii_rxc;
input rgmii_rx_ctl;
input [3:0] rgmii_rxd;
output gmii_rx_clk;
output gmii_rx_dv;
output gmii_rx_er;
output [7:0] gmii_rxd;

hme_ip_rgmii_tx u_tx (
        .clk_eth (clk_eth),
        .clk_eth_90d (clk_eth_90d),
        .i_tx_clk_d0 (i_tx_clk_d0),
        .i_tx_clk_d1 (i_tx_clk_d1),
        .gmii_tx_en (gmii_tx_en),
        .gmii_txd (gmii_txd),
        .gmii_tx_er (gmii_tx_er),
        .rgmii_txc (rgmii_txc),
        .rgmii_tx_ctl (rgmii_tx_ctl),
        .rgmii_txd (rgmii_txd)
);
hme_ip_rgmii_rx #( .PDIV (1'b0) ) u_rx (
        .rgmii_rxc (rgmii_rxc),
        .rgmii_rx_ctl (rgmii_rx_ctl),
        .rgmii_rxd (rgmii_rxd),
        .gmii_rx_clk (gmii_rx_clk),
        .gmii_rx_dv (gmii_rx_dv),
        .gmii_rx_er (gmii_rx_er),
        .gmii_rxd (gmii_rxd)
);

endmodule

// ============================================================
//                  rgmii Setting
//
// Warning: This part is read by Fuxi, please don't modify it.
// ============================================================
// Device          : H7P20N0V213-S1H1C7
// Module          : rgmii_v1
// IP core         : rgmii
// IP Version      : 1

// PDIV            : true
// Sdc Files       : sdc/rgmii_v1.sdc
// Simulation Files: ../ip_core/rgmii_v1/sim/src/P0/hme_ip_rgmii_tx.v ../ip_core/rgmii_v1/sim/src/P0/hme_ip_rgmii_rx.v
// Synthesis Files : src/P0_P2/hme_ip_rgmii_tx.v src/P0_P2/hme_ip_rgmii_rx.v
