//
// This is a file generated by SOC System wizard.
// Please do not edit this file!
// Generated time: 07/13/2025 15:31:33
// Version: Fuxi fx2023.1 win64
// Wizard name: SOC System 1.0b
//
// ============================================================
// File Name: soc_system_v1.v
// IP core : soc_system
// Device name: H7P20N0L128-M3H1C7
// ============================================================

module soc_system_v1(
    m3soc_clk_o,
    m3soc_clken,
    m3soc_rstn,
    u_m3soc_gpio0_ext_porta_i,
    u_m3soc_gpio0_porta_ddr_o,
    u_m3soc_gpio0_porta_dr_o,
    u_m3soc_fp_clk,
    u_m3soc_fp_rst_n,
    hclk_fp_brg_gate,
    u_m3soc_hrdata_s1_fp,
    u_m3soc_hready_resp_s1_fp,
    u_m3soc_hresp_s1_fp,
    u_m3soc_haddr_s1_fp,
    u_m3soc_hburst_s1_fp,
    u_m3soc_hsize_s1_fp,
    u_m3soc_htrans_s1_fp,
    u_m3soc_hwdata_s1_fp,
    u_m3soc_hwrite_s1_fp,
    u_m3soc_ic0_clk_in_a,
    u_m3soc_ic0_clk_oe,
    u_m3soc_ic0_data_in_a_i,
    u_m3soc_ic0_data_oe_o,
    u_m3soc_spi0_clk_in_i,
    u_m3soc_spi0_cs_n_in_i,
    u_m3soc_spi0_clk_oe_o,
    u_m3soc_spi0_clk_out_o,
    u_m3soc_spi0_cs_n_oe_o,
    u_m3soc_spi0_cs_n_out_o,
    u_m3soc_spi0_mosi_in_i,
    u_m3soc_spi0_mosi_oe_o,
    u_m3soc_spi0_mosi_out_o,
    u_m3soc_spi0_miso_in_i,
    u_m3soc_spi0_miso_oe_o,
    u_m3soc_spi0_miso_out_o,
    u_m3soc_spi0_hold_n_in_i,
    u_m3soc_spi0_hold_n_oe_o,
    u_m3soc_spi0_hold_n_out_o,
    u_m3soc_spi0_wp_n_in_i,
    u_m3soc_spi0_wp_n_oe_o,
    u_m3soc_spi0_wp_n_out_o,
    u_m3soc_uart0_cts_n_i,
    u_m3soc_uart0_dcd_n_i,
    u_m3soc_uart0_dsr_n_i,
    u_m3soc_uart0_ri_n_i,
    u_m3soc_uart0_dtr_n_o,
    u_m3soc_uart0_out1_n_o,
    u_m3soc_uart0_out2_n_o,
    u_m3soc_uart0_rts_n_o,
    u_m3soc_uart0_sin_i,
    u_m3soc_uart0_sout_o,
    u_m3soc_uart0_sir_in_i,
    u_m3soc_uart0_sir_out_n_o,
    u_m3soc_uart0_baudout_n_o,
    u_m3soc_fp_intr
);

input m3soc_clk_o;
input m3soc_clken;
input m3soc_rstn;
input [31:0] u_m3soc_gpio0_ext_porta_i;
output [31:0] u_m3soc_gpio0_porta_ddr_o;
output [31:0] u_m3soc_gpio0_porta_dr_o;
input u_m3soc_fp_clk;
input u_m3soc_fp_rst_n;
output hclk_fp_brg_gate;
input [31:0] u_m3soc_hrdata_s1_fp;
input u_m3soc_hready_resp_s1_fp;
input [1:0] u_m3soc_hresp_s1_fp;
output [31:0] u_m3soc_haddr_s1_fp;
output [2:0] u_m3soc_hburst_s1_fp;
output [2:0] u_m3soc_hsize_s1_fp;
output [1:0] u_m3soc_htrans_s1_fp;
output [31:0] u_m3soc_hwdata_s1_fp;
output u_m3soc_hwrite_s1_fp;
input u_m3soc_ic0_clk_in_a;
output u_m3soc_ic0_clk_oe;
input u_m3soc_ic0_data_in_a_i;
output u_m3soc_ic0_data_oe_o;
input u_m3soc_spi0_clk_in_i;
input u_m3soc_spi0_cs_n_in_i;
output u_m3soc_spi0_clk_oe_o;
output u_m3soc_spi0_clk_out_o;
output u_m3soc_spi0_cs_n_oe_o;
output u_m3soc_spi0_cs_n_out_o;
input u_m3soc_spi0_mosi_in_i;
output u_m3soc_spi0_mosi_oe_o;
output u_m3soc_spi0_mosi_out_o;
input u_m3soc_spi0_miso_in_i;
output u_m3soc_spi0_miso_oe_o;
output u_m3soc_spi0_miso_out_o;
input u_m3soc_spi0_hold_n_in_i;
output u_m3soc_spi0_hold_n_oe_o;
output u_m3soc_spi0_hold_n_out_o;
input u_m3soc_spi0_wp_n_in_i;
output u_m3soc_spi0_wp_n_oe_o;
output u_m3soc_spi0_wp_n_out_o;
input u_m3soc_uart0_cts_n_i;
input u_m3soc_uart0_dcd_n_i;
input u_m3soc_uart0_dsr_n_i;
input u_m3soc_uart0_ri_n_i;
output u_m3soc_uart0_dtr_n_o;
output u_m3soc_uart0_out1_n_o;
output u_m3soc_uart0_out2_n_o;
output u_m3soc_uart0_rts_n_o;
input u_m3soc_uart0_sin_i;
output u_m3soc_uart0_sout_o;
input u_m3soc_uart0_sir_in_i;
output u_m3soc_uart0_sir_out_n_o;
output u_m3soc_uart0_baudout_n_o;
input [16:0] u_m3soc_fp_intr;
soc_top #(
        .PSRAM_LOC (18'b000000000100000001),
        .DEBUG_EN (1'b1),
        .fp_interface_en (21'b100000000100100100110),
        .program_file ("../mcu_base_ethernet_mac_v3_example/Objects/HME_MCU.hex")
)
u_m3soc_top (
        .m3soc_clk_o (m3soc_clk_o),
        .m3soc_clken (m3soc_clken),
        .m3soc_rstn (m3soc_rstn),
        .u_m3soc_fp_clk (u_m3soc_fp_clk),
        .u_m3soc_fp_rst_n (u_m3soc_fp_rst_n),
        .hclk_fp_brg_gate (hclk_fp_brg_gate),
        .u_m3soc_hrdata_s1_fp (u_m3soc_hrdata_s1_fp),
        .u_m3soc_hready_resp_s1_fp (u_m3soc_hready_resp_s1_fp),
        .u_m3soc_hresp_s1_fp (u_m3soc_hresp_s1_fp),
        .u_m3soc_haddr_s1_fp (u_m3soc_haddr_s1_fp),
        .u_m3soc_hburst_s1_fp (u_m3soc_hburst_s1_fp),
        .u_m3soc_hsize_s1_fp (u_m3soc_hsize_s1_fp),
        .u_m3soc_htrans_s1_fp (u_m3soc_htrans_s1_fp),
        .u_m3soc_hwdata_s1_fp (u_m3soc_hwdata_s1_fp),
        .u_m3soc_hwrite_s1_fp (u_m3soc_hwrite_s1_fp),
        .u_m3soc_gpio0_ext_porta_i (u_m3soc_gpio0_ext_porta_i),
        .u_m3soc_gpio0_porta_ddr_o (u_m3soc_gpio0_porta_ddr_o),
        .u_m3soc_gpio0_porta_dr_o (u_m3soc_gpio0_porta_dr_o),
        .u_m3soc_gpio1_ext_porta_i (),
        .u_m3soc_gpio1_porta_ddr_o (),
        .u_m3soc_gpio1_porta_dr_o (),
        .u_m3soc_ic0_clk_in_a (u_m3soc_ic0_clk_in_a),
        .u_m3soc_ic0_clk_oe (u_m3soc_ic0_clk_oe),
        .u_m3soc_ic0_data_in_a_i (u_m3soc_ic0_data_in_a_i),
        .u_m3soc_ic0_data_oe_o (u_m3soc_ic0_data_oe_o),
        .u_m3soc_ic1_clk_in_a (),
        .u_m3soc_ic1_clk_oe (),
        .u_m3soc_ic1_data_in_a_i (),
        .u_m3soc_ic1_data_oe_o (),
        .u_m3soc_ic2_clk_in_a (),
        .u_m3soc_ic2_clk_oe (),
        .u_m3soc_ic2_data_in_a_i (),
        .u_m3soc_ic2_data_oe_o (),
        .u_m3soc_spi0_clk_in_i (u_m3soc_spi0_clk_in_i),
        .u_m3soc_spi0_cs_n_in_i (u_m3soc_spi0_cs_n_in_i),
        .u_m3soc_spi0_clk_oe_o (u_m3soc_spi0_clk_oe_o),
        .u_m3soc_spi0_clk_out_o (u_m3soc_spi0_clk_out_o),
        .u_m3soc_spi0_cs_n_oe_o (u_m3soc_spi0_cs_n_oe_o),
        .u_m3soc_spi0_cs_n_out_o (u_m3soc_spi0_cs_n_out_o),
        .u_m3soc_spi0_mosi_in_i (u_m3soc_spi0_mosi_in_i),
        .u_m3soc_spi0_mosi_oe_o (u_m3soc_spi0_mosi_oe_o),
        .u_m3soc_spi0_mosi_out_o (u_m3soc_spi0_mosi_out_o),
        .u_m3soc_spi0_miso_in_i (u_m3soc_spi0_miso_in_i),
        .u_m3soc_spi0_miso_oe_o (u_m3soc_spi0_miso_oe_o),
        .u_m3soc_spi0_miso_out_o (u_m3soc_spi0_miso_out_o),
        .u_m3soc_spi0_hold_n_in_i (u_m3soc_spi0_hold_n_in_i),
        .u_m3soc_spi0_hold_n_oe_o (u_m3soc_spi0_hold_n_oe_o),
        .u_m3soc_spi0_hold_n_out_o (u_m3soc_spi0_hold_n_out_o),
        .u_m3soc_spi0_wp_n_in_i (u_m3soc_spi0_wp_n_in_i),
        .u_m3soc_spi0_wp_n_oe_o (u_m3soc_spi0_wp_n_oe_o),
        .u_m3soc_spi0_wp_n_out_o (u_m3soc_spi0_wp_n_out_o),
        .u_m3soc_spi1_clk_in_i (),
        .u_m3soc_spi1_cs_n_in_i (),
        .u_m3soc_spi1_clk_oe_o (),
        .u_m3soc_spi1_clk_out_o (),
        .u_m3soc_spi1_cs_n_oe_o (),
        .u_m3soc_spi1_cs_n_out_o (),
        .u_m3soc_spi1_mosi_in_i (),
        .u_m3soc_spi1_mosi_oe_o (),
        .u_m3soc_spi1_mosi_out_o (),
        .u_m3soc_spi1_miso_in_i (),
        .u_m3soc_spi1_miso_oe_o (),
        .u_m3soc_spi1_miso_out_o (),
        .u_m3soc_spi1_hold_n_in_i (),
        .u_m3soc_spi1_hold_n_oe_o (),
        .u_m3soc_spi1_hold_n_out_o (),
        .u_m3soc_spi1_wp_n_in_i (),
        .u_m3soc_spi1_wp_n_oe_o (),
        .u_m3soc_spi1_wp_n_out_o (),
        .u_m3soc_spi2_clk_in_i (),
        .u_m3soc_spi2_cs_n_in_i (),
        .u_m3soc_spi2_clk_oe_o (),
        .u_m3soc_spi2_clk_out_o (),
        .u_m3soc_spi2_cs_n_oe_o (),
        .u_m3soc_spi2_cs_n_out_o (),
        .u_m3soc_spi2_mosi_in_i (),
        .u_m3soc_spi2_mosi_oe_o (),
        .u_m3soc_spi2_mosi_out_o (),
        .u_m3soc_spi2_miso_in_i (),
        .u_m3soc_spi2_miso_oe_o (),
        .u_m3soc_spi2_miso_out_o (),
        .u_m3soc_spi2_hold_n_in_i (),
        .u_m3soc_spi2_hold_n_oe_o (),
        .u_m3soc_spi2_hold_n_out_o (),
        .u_m3soc_spi2_wp_n_in_i (),
        .u_m3soc_spi2_wp_n_oe_o (),
        .u_m3soc_spi2_wp_n_out_o (),
        .u_m3soc_uart0_cts_n_i (u_m3soc_uart0_cts_n_i),
        .u_m3soc_uart0_dcd_n_i (u_m3soc_uart0_dcd_n_i),
        .u_m3soc_uart0_dsr_n_i (u_m3soc_uart0_dsr_n_i),
        .u_m3soc_uart0_ri_n_i (u_m3soc_uart0_ri_n_i),
        .u_m3soc_uart0_dtr_n_o (u_m3soc_uart0_dtr_n_o),
        .u_m3soc_uart0_out1_n_o (u_m3soc_uart0_out1_n_o),
        .u_m3soc_uart0_out2_n_o (u_m3soc_uart0_out2_n_o),
        .u_m3soc_uart0_rts_n_o (u_m3soc_uart0_rts_n_o),
        .u_m3soc_uart0_sin_i (u_m3soc_uart0_sin_i),
        .u_m3soc_uart0_sout_o (u_m3soc_uart0_sout_o),
        .u_m3soc_uart0_sir_in_i (u_m3soc_uart0_sir_in_i),
        .u_m3soc_uart0_sir_out_n_o (u_m3soc_uart0_sir_out_n_o),
        .u_m3soc_uart0_baudout_n_o (u_m3soc_uart0_baudout_n_o),
        .u_m3soc_uart1_cts_n_i (),
        .u_m3soc_uart1_dcd_n_i (),
        .u_m3soc_uart1_dsr_n_i (),
        .u_m3soc_uart1_ri_n_i (),
        .u_m3soc_uart1_dtr_n_o (),
        .u_m3soc_uart1_out1_n_o (),
        .u_m3soc_uart1_out2_n_o (),
        .u_m3soc_uart1_rts_n_o (),
        .u_m3soc_uart1_sin_i (),
        .u_m3soc_uart1_sout_o (),
        .u_m3soc_uart1_sir_in_i (),
        .u_m3soc_uart1_sir_out_n_o (),
        .u_m3soc_uart1_baudout_n_o (),
        .u_m3soc_uart2_cts_n_i (),
        .u_m3soc_uart2_dcd_n_i (),
        .u_m3soc_uart2_dsr_n_i (),
        .u_m3soc_uart2_ri_n_i (),
        .u_m3soc_uart2_dtr_n_o (),
        .u_m3soc_uart2_out1_n_o (),
        .u_m3soc_uart2_out2_n_o (),
        .u_m3soc_uart2_rts_n_o (),
        .u_m3soc_uart2_sin_i (),
        .u_m3soc_uart2_sout_o (),
        .u_m3soc_uart2_sir_in_i (),
        .u_m3soc_uart2_sir_out_n_o (),
        .u_m3soc_uart2_baudout_n_o (),
        .u_m3soc_soc_intr (u_m3soc_soc_intr),
        .u_m3soc_fp_intr (u_m3soc_fp_intr)
);
endmodule

// ============================================================
//                  soc_system Setting
//
// Warning: This part is read by Fuxi, please don't modify it.
// ============================================================
// Device          : H7P20N0L128-M3H1C7
// Module          : soc_system_v1
// IP core         : soc_system
// IP Version      : 1

// DebugEnable     : true
// HexFile         : ../mcu_base_ethernet_mac_v3_example/Objects/HME_MCU.hex
// PSRAM0          : true
// PSRAM1          : false
// PSRAM10         : false
// PSRAM11         : false
// PSRAM12         : false
// PSRAM13         : false
// PSRAM14         : false
// PSRAM15         : false
// PSRAM16         : false
// PSRAM17         : false
// PSRAM2          : false
// PSRAM3          : false
// PSRAM4          : false
// PSRAM5          : false
// PSRAM6          : false
// PSRAM7          : false
// PSRAM8          : true
// PSRAM9          : false
// Simulation Files: 
// Synthesis Files : 
// UseAHBClock     : true
// UseAHBMaster    : false
// UseAHBSlave     : true
// UseAPBSlaveforFP: false
// UseDmaAck       : false
// UseDmaAckI2c0   : false
// UseDmaAckI2c1   : false
// UseDmaAckI2c2   : false
// UseDmaAckSpi0   : false
// UseDmaAckSpi1   : false
// UseDmaAckSpi2   : false
// UseDmaAckSpi3   : false
// UseDmaAckUart0  : false
// UseDmaAckUart1  : false
// UseDmaAckUart2  : false
// UseDmaReq       : false
// UseDmaReqI2c0   : false
// UseDmaReqI2c1   : false
// UseDmaReqI2c2   : false
// UseDmaReqSpi0   : false
// UseDmaReqSpi1   : false
// UseDmaReqSpi2   : false
// UseDmaReqSpi3   : false
// UseDmaReqUart0  : false
// UseDmaReqUart1  : false
// UseDmaReqUart2  : false
// UseDmaSingle    : false
// UseEfuseOut     : false
// UseEventCommunication: false
// UseExternalDmaSupport: false
// UseGPIO0        : true
// UseGPIO1        : false
// UseI2C0         : true
// UseI2C1         : false
// UseI2C2         : false
// UseInterruption : true
// UseIntrDmaIntr  : false
// UseIntrFPIntr   : true
// UseIntrGPIO0    : false
// UseIntrGPIO1    : false
// UseIntrI2C0     : false
// UseIntrI2C1     : false
// UseIntrI2C2     : false
// UseIntrQSPI     : false
// UseIntrSPI0     : false
// UseIntrSPI1     : false
// UseIntrSPI2     : false
// UseIntrSocIntr  : false
// UseIntrSysCtrl  : false
// UseIntrTimer0   : false
// UseIntrTimer1   : false
// UseIntrUART0    : false
// UseIntrUART1    : false
// UseIntrUART2    : false
// UseIntrWDT      : false
// UseSPI0         : true
// UseSPI1         : false
// UseSPI2         : false
// UseSRAMforFP    : false
// UseSocClken     : true
// UseSocClko      : true
// UseSocRstn      : true
// UseUART0        : true
// UseUART1        : false
// UseUART2        : false
