//
// This is a file generated by Debugware wizard.
// Please do not edit this file!
// Generated time: 01/01/2015 00:21:25
// Version: Fuxi fx2023.1 win64
// Wizard name: Debugware 2.1a
//
// ============================================================
// File Name: debugware_v2_1.v
// IP core : debugware
// Device name: H7P20N0L128-M3H1C7
// ============================================================

module debugware_v2_1(
    trig_out_0,
    data_in_0,
    ref_clk_0
);

output trig_out_0;
input [15:0] data_in_0;
input ref_clk_0;

wire tck1, tdi1, tdo1, sel1, tck2, tdi2, tdo2, sel2, update, shift, reset;
wire [0:0] la_sel;
wire [0:0] la_tdo;
wire status, ctrl, offset, mem, la_reset, la_tck, la_tdi, la_shift, la_update;
tap #( .DEVICE_NAME (4) ) u_tap (
        .tck1 (tck1),
        .tdi1 (tdi1),
        .tdo1 (tdo1),
        .sel1 (sel1),
        .tck2 (tck2),
        .tdi2 (tdi2),
        .tdo2 (tdo2),
        .sel2 (sel2),
        .update (update),
        .shift (shift),
        .reset (reset)
);
wire update_clk;
GBUF u_gbuf_update (
        .in (update),
        .out (update_clk)
);
la_manager #( .NUM_OF_LA (1) ) u_la_manager (
        .tck1 (tck1),
        .tdi1 (tdi1),
        .tdo1 (tdo1),
        .sel1 (sel1),
        .tck2 (tck2),
        .tdi2 (tdi2),
        .tdo2 (tdo2),
        .sel2 (sel2),
        .update (update),
        .update_clk (update_clk),
        .shift (shift),
        .reset (reset),
        .la_sel (la_sel),
        .status (status),
        .ctrl (ctrl),
        .mem (mem),
        .offset (offset),
        .la_reset (la_reset),
        .la_tck (la_tck),
        .la_update (la_update),
        .la_shift (la_shift),
        .la_tdi (la_tdi),
        .la_tdo (la_tdo)
);
la_core #(
        .DATA_WIDTH (16),
        .SAMPLE_DEPTH (8192),
        .ADDR_WIDTH (13),
        .INPUT_DFF_LEVEL (0),
        .DEVICE_NAME (4)
)
u_la_core_0 (
        .sel (la_sel[0]),
        .status_sel (status),
        .ctrl_sel (ctrl),
        .mem_sel (mem),
        .offset_sel (offset),
        .reset (la_reset&la_sel[0]),
        .tck (la_tck),
        .update (la_update),
        .shift (la_shift),
        .tdi (la_tdi),
        .tdo (la_tdo[0]),
        .trig_out (trig_out_0),
        .data_in (data_in_0),
        .ref_clk (ref_clk_0),
        .reset_raddr (update&mem&sel1),
        .mem_read (update_clk)
);

endmodule

// ============================================================
//                  debugware Setting
//
// Warning: This part is read by Fuxi, please don't modify it.
// ============================================================
// Device          : H7P20N0L128-M3H1C7
// Module          : debugware_v2_1
// IP core         : debugware
// IP Version      : 2_1

// LA0_CoreName    : 
// LA0_InputDFFLevel: 0
// LA0_StorageDepth: 13
// LA0_StorageWidth: 16
// LaCoreCount     : 1
// Simulation Files: 
// Synthesis Files : src/dwip.v
